[package]
name = "hacker-term"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.9", package = "gtk4" }
gio = "0.9"
glib = "0.10"
vte = { version = "0.13", package = "vte4" }
webkitgtk6 = "0.2"
which = "4.4"
